//引入path
const path = require('path');
module.exports={
    //入口
    //多入口
    entry:{
        //前面的参数名，随便定义，后面的URL路径
        entry:'./src/entry.js',
        entry2:'./src/entry2.js'
    },
    //出口
    output:{
        //多出口中，path唯一的
        //filename ：中的[name]是打包的文件和入口文件名保持一致
        path:path.resolve(__dirname,'dist'),
        filename:'[name].js'
    },
    //配置
    module:{},
    //插件，可以有多个插件
    plugins:[],
    //webpack服务
    devServer:{
        //指定需要更新的目录
        contentBase:path.resolve(__dirname,'dist'),
        //服务器地址
        host:'192.168.1.100',
        //服务器压缩
        compress:true,
        //端口，默认为80
        port:80
    }
}